image: osrf/ros2:nightly

build:
  stage: build
  script:
  - pip3 install -U pytest colcon-common-extensions
  - mkdir -p /workspace/src
  - cp -r $(pwd) /workspace/src/ros2_v4l2_camera
  - cd /workspace
  - git clone --branch 2.0.1 --depth 1 https://github.com/ros-perception/image_common.git src/image_common
  - colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug
